name: build-pdfs
concurrency: build-pdfs
on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Images for slides
        run: mkdir -p build/transparencias && cp -R transparencias/img build/transparencias/img

      - name: Slides in HTML
        uses: docker://marpteam/marp-cli:v1.7.0
        with:
          args: -I transparencias/ -o build/transparencias/ --html --allow-local-files
        env:
          MARP_USER: root:root

      - name: Slides in PDF
        uses: docker://marpteam/marp-cli:v1.7.0
        with:
          args: -I transparencias/ -o build/transparencias/ --html --pdf --allow-local-files
        env:
          MARP_USER: root:root

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: "*.tex"
          working_directory: ejercicios

      - name: Copy pdf files
        run: mkdir -p build/ejercicios  && cp ejercicios/*.pdf build/ejercicios
        
      - name: Deploy preview
        if: ${{ github.event_name == 'pull_request' }}
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/
          preview-branch: gh-pages
          umbrella-dir: pr-preview

      - name: Deploy production
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./build/
          clean-exclude: pr-preview/
